import { BRAND, LOGO } from "./logo-data";

export type LogoTone = "light" | "dark";

/** Geometry shared by the inline <Logo> and the static lockup files, so both always match. */
export function logoLayout(tagline: boolean) {
  // Without the tagline the wordmark is centred on the mark's height instead of sitting on its top edge.
  const viewH = tagline ? LOGO.height : LOGO.mark.height + 1.8;
  const wordShift = tagline ? 0 : (LOGO.mark.height - 52.5) / 2;
  return { viewW: LOGO.width, viewH, wordShift };
}

/** Public path of the static lockup (generated by `scripts/generate-brand-assets.ts`). */
export const lockupPath = (tone: LogoTone, tagline: boolean) => `/brand/lockup-${tone}${tagline ? "-tagline" : ""}.svg`;

/** Standalone SVG document of the lockup with explicit colours (an <img> has no currentColor to inherit). */
export function lockupSvg(tone: LogoTone, tagline: boolean): string {
  const { viewW, viewH, wordShift } = logoLayout(tagline);
  const text = tone === "dark" ? "#FFFFFF" : BRAND.charcoal;
  const l = tone === "dark" ? "#FFFFFF" : BRAND.orange;
  const shift = wordShift ? ` transform="translate(0 ${wordShift.toFixed(2)})"` : "";
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${viewW} ${viewH}">`,
    `<path d="${LOGO.markE}" fill="${BRAND.orange}"/>`,
    `<path d="${LOGO.markL}" fill="${l}"/>`,
    `<path d="${LOGO.wordmark}" fill="${text}"${shift}/>`,
    tagline ? `<path d="${LOGO.tagline}" fill="${text}"/>` : "",
    `</svg>\n`,
  ].join("");
}
