import type { Prisma } from "@prisma/client";

export const categories = [
  { slug: "it", name: "IT va dasturlash", order: 0 },
  { slug: "ai-robotics", name: "AI va robototexnika", order: 1 },
  { slug: "kids", name: "Bolalar uchun", order: 2 },
  { slug: "creative", name: "Kreativ va media", order: 3 },
  { slug: "marketing", name: "Marketing", order: 4 },
  { slug: "soft-skills", name: "Shaxsiy rivojlanish", order: 5 },
];

type CourseSeed = Omit<Prisma.CourseUncheckedCreateInput, "categoryId"> & { category: string };

/**
 * Nine directions from the business brief. Duration, schedule and price fields are
 * editorial placeholders and must be confirmed in the admin panel before publishing.
 */
export const courses: CourseSeed[] = [
  {
    slug: "dasturlash",
    title: "Dasturlash",
    roleLabel: "Developer",
    tagline: "Real mahsulotlar yarating.",
    description:
      "Noldan boshlab web-dasturlashni oʻrganing: HTML, CSS, JavaScript, zamonaviy frontend va backend asoslari. Kurs davomida siz haqiqiy loyihalar ustida ishlaysiz va bitiruvda portfolio bilan chiqasiz.",
    category: "it",
    level: "BEGINNER",
    format: "OFFLINE",
    durationLabel: "8 oy",
    durationWeeks: 32,
    schedule: "Haftasiga 3 kun · 90 daqiqa",
    ageLabel: "14+",
    accent: "#FF6B1A",
    whoFor: ["Dasturlashni noldan boshlamoqchi boʻlganlar", "IT sohasiga kasb sifatida kirmoqchi boʻlgan yoshlar", "Oʻz gʻoyasini mahsulotga aylantirmoqchi boʻlganlar"],
    skills: ["HTML & CSS", "JavaScript", "TypeScript", "React", "Node.js", "Git & GitHub", "REST API", "Ma'lumotlar bazasi"],
    outcomes: ["Junior Developer sifatida ishga kirish", "Oʻz web-loyihangizni ishga tushirish", "Freelance buyurtmalarni bajarish", "Portfolio: kamida 3 ta real loyiha"],
    curriculum: [
      { title: "Web asoslari", lessons: ["Internet qanday ishlaydi", "HTML semantikasi", "CSS layout: Flexbox, Grid", "Responsive dizayn"] },
      { title: "JavaScript", lessons: ["Tillar asoslari", "DOM va hodisalar", "Asinxron kod", "API bilan ishlash"] },
      { title: "Frontend", lessons: ["React komponentlari", "State boshqaruvi", "Routing", "Real loyiha"] },
      { title: "Backend asoslari", lessons: ["Node.js", "REST API", "Ma'lumotlar bazasi", "Autentifikatsiya"] },
      { title: "Diplom loyihasi", lessons: ["Gʻoya va rejalashtirish", "Jamoaviy ishlab chiqish", "Deploy", "Himoya"] },
    ],
    projects: [
      { title: "Shaxsiy portfolio sayt", description: "Responsive, animatsiyali sayt" },
      { title: "Onlayn doʻkon", description: "Savat, toʻlov va admin bilan" },
      { title: "Jamoaviy startap loyiha", description: "Haqiqiy foydalanuvchilar uchun" },
    ],
    featured: true,
    order: 0,
    status: "PUBLISHED",
  },
  {
    slug: "robototexnika",
    title: "Robototexnika",
    roleLabel: "Robotics Engineer",
    tagline: "Gʻoyani harakatga keltiring.",
    description:
      "Arduino va sensorlar bilan ishlashdan boshlab, avtonom robotlar yaratishgacha. Elektronika, mexanika va dasturlash — bir kursda.",
    category: "ai-robotics",
    level: "BEGINNER",
    format: "OFFLINE",
    durationLabel: "6 oy",
    durationWeeks: 24,
    schedule: "Haftasiga 2 kun · 120 daqiqa",
    ageLabel: "10+",
    accent: "#FF8A3D",
    whoFor: ["Texnikaga qiziquvchi oʻquvchilar", "Muhandislik yoʻnalishiga kirmoqchi boʻlganlar", "Olimpiada va musobaqalarga tayyorlanuvchilar"],
    skills: ["Arduino", "Elektronika asoslari", "Sensorlar", "C/C++", "3D modellashtirish", "Mexanika"],
    outcomes: ["Oʻz robotingizni loyihalash va yigʻish", "Robototexnika musobaqalarida qatnashish", "Muhandislik fikrlash asoslari"],
    curriculum: [
      { title: "Elektronika asoslari", lessons: ["Tok, kuchlanish, qarshilik", "Sxemalar", "Breadboard bilan ishlash"] },
      { title: "Arduino", lessons: ["Mikrokontroller", "Sensorlar", "Motorlar", "Dasturlash"] },
      { title: "Robot yaratish", lessons: ["Chiziq boʻylab yuruvchi robot", "Toʻsiqdan qochuvchi robot", "Masofadan boshqarish"] },
      { title: "Loyiha", lessons: ["Oʻz robotingiz", "Taqdimot"] },
    ],
    projects: [{ title: "Avtonom robot", description: "Sensorlar orqali yoʻl topuvchi robot" }],
    order: 1,
    status: "PUBLISHED",
  },
  {
    slug: "ai",
    title: "Sunʼiy intellekt",
    roleLabel: "AI Specialist",
    tagline: "Kelajak vositalarini bugun egallang.",
    description:
      "Python asoslaridan boshlab, maʼlumotlar tahlili va zamonaviy AI vositalari (LLM, generativ modellar) bilan ishlashgacha. Amaliy loyihalar orqali AI'ni real muammolarga qoʻllashni oʻrganasiz.",
    category: "ai-robotics",
    level: "INTERMEDIATE",
    format: "HYBRID",
    durationLabel: "6 oy",
    durationWeeks: 24,
    schedule: "Haftasiga 3 kun · 90 daqiqa",
    ageLabel: "16+",
    accent: "#FF5C00",
    whoFor: ["Python bilan tanish boʻlganlar", "Maʼlumotlar bilan ishlashni istaganlar", "AI vositalarini biznesda qoʻllamoqchi boʻlganlar"],
    skills: ["Python", "Pandas & NumPy", "Machine Learning", "Neural Networks", "LLM va prompt engineering", "AI avtomatlashtirish"],
    outcomes: ["Maʼlumotlar tahlili loyihalarini bajarish", "AI vositalari bilan ish jarayonlarini avtomatlashtirish", "Oʻz AI loyihangizni yaratish"],
    curriculum: [
      { title: "Python va maʼlumotlar", lessons: ["Python asoslari", "Pandas", "Vizualizatsiya"] },
      { title: "Machine Learning", lessons: ["Regressiya va klassifikatsiya", "Model baholash", "Amaliy keys"] },
      { title: "Neyron tarmoqlar", lessons: ["Asoslar", "Tasvir va matn", "Transfer learning"] },
      { title: "Generativ AI", lessons: ["LLM bilan ishlash", "Prompt engineering", "AI agentlar", "Loyiha"] },
    ],
    projects: [{ title: "AI yordamchi", description: "Biznes uchun chatbot yoki avtomatlashtirish" }],
    featured: true,
    order: 2,
    status: "PUBLISHED",
  },
  {
    slug: "it-kids",
    title: "IT-KIDS",
    roleLabel: "Young Creator",
    tagline: "Oʻyin orqali texnologiya.",
    description:
      "Bolalar uchun dasturlash va texnologiya olamiga birinchi qadam. Scratch, oʻyin yaratish va mantiqiy fikrlash — qiziqarli va tushunarli shaklda.",
    category: "kids",
    level: "BEGINNER",
    format: "OFFLINE",
    durationLabel: "4 oy",
    durationWeeks: 16,
    schedule: "Haftasiga 2 kun · 60 daqiqa",
    ageLabel: "7–12",
    accent: "#FFA05C",
    whoFor: ["7–12 yoshli bolalar", "Kompyuterga qiziqadigan farzandlar", "Mantiqiy fikrlashni rivojlantirmoqchi boʻlganlar"],
    skills: ["Scratch", "Algoritmik fikrlash", "Oʻyin dizayni", "Kompyuter savodxonligi", "Jamoada ishlash"],
    outcomes: ["Oʻz oʻyinini yaratish", "Dasturlash asoslarini tushunish", "Katta kurslarga tayyorgarlik"],
    curriculum: [
      { title: "Kompyuter dunyosi", lessons: ["Kompyuter bilan doʻstlashish", "Internet xavfsizligi"] },
      { title: "Scratch", lessons: ["Birinchi animatsiya", "Oʻyin mexanikasi", "Oʻz oʻyinim"] },
      { title: "Loyiha", lessons: ["Jamoaviy oʻyin", "Taqdimot"] },
    ],
    order: 3,
    status: "PUBLISHED",
  },
  {
    slug: "notiqlik",
    title: "Notiqlik",
    roleLabel: "Public Speaker",
    tagline: "Fikringiz eshitilsin.",
    description:
      "Ommaviy nutq, ishonchli muloqot va taqdimot sanʼati. Kamera va sahna oldida oʻzini erkin his qilish, fikrni aniq va taʼsirli yetkazish.",
    category: "soft-skills",
    level: "BEGINNER",
    format: "OFFLINE",
    durationLabel: "3 oy",
    durationWeeks: 12,
    schedule: "Haftasiga 2 kun · 90 daqiqa",
    ageLabel: "14+",
    accent: "#FF7A2E",
    whoFor: ["Nutq soʻzlashdan qoʻrqadiganlar", "Rahbarlar va tadbirkorlar", "Bloger va kontent yaratuvchilar"],
    skills: ["Nutq tuzilishi", "Ovoz va diksiya", "Tana tili", "Improvizatsiya", "Taqdimot", "Kamera oldida gapirish"],
    outcomes: ["Auditoriya oldida ishonch bilan gapirish", "Taʼsirli taqdimot qilish", "Intervyu va muzokaralarda oʻzini tutish"],
    curriculum: [
      { title: "Asoslar", lessons: ["Qoʻrquvni yengish", "Ovoz bilan ishlash", "Diksiya"] },
      { title: "Nutq sanʼati", lessons: ["Nutq strukturasi", "Storytelling", "Argumentatsiya"] },
      { title: "Amaliyot", lessons: ["Kamera oldida", "Sahna", "Yakuniy nutq"] },
    ],
    order: 4,
    status: "PUBLISHED",
  },
  {
    slug: "mobilografiya",
    title: "Mobilografiya",
    roleLabel: "Mobile Content Creator",
    tagline: "Telefon — sizning studiyangiz.",
    description:
      "Smartfon bilan professional darajada foto va video olish, montaj qilish va ijtimoiy tarmoqlar uchun kontent yaratish.",
    category: "creative",
    level: "BEGINNER",
    format: "OFFLINE",
    durationLabel: "2 oy",
    durationWeeks: 8,
    schedule: "Haftasiga 3 kun · 90 daqiqa",
    ageLabel: "14+",
    accent: "#FF6B1A",
    whoFor: ["Bloger boʻlmoqchi boʻlganlar", "Oʻz biznesini oʻzi suratga olmoqchi boʻlganlar", "SMM mutaxassislari"],
    skills: ["Kompozitsiya", "Yorugʻlik", "Mobil video", "CapCut / VN montaj", "Rang korreksiyasi", "Reels formatlari"],
    outcomes: ["Telefonda sifatli kontent yaratish", "Reels va Stories uchun montaj", "Shaxsiy vizual uslub"],
    curriculum: [
      { title: "Foto", lessons: ["Kompozitsiya", "Yorugʻlik", "Mobil tahrir"] },
      { title: "Video", lessons: ["Kadr va harakat", "Ovoz", "Montaj"] },
      { title: "Kontent", lessons: ["Reels dramaturgiyasi", "Trendlar", "Loyiha"] },
    ],
    order: 5,
    status: "PUBLISHED",
  },
  {
    slug: "videografiya",
    title: "Videografiya",
    roleLabel: "Videographer",
    tagline: "Har bir kadr — hikoya.",
    description:
      "Professional kamera, yorugʻlik va montaj bilan ishlash. Reklama roliklari, YouTube kontent va tadbirlar uchun video ishlab chiqarish toʻliq jarayoni.",
    category: "creative",
    level: "INTERMEDIATE",
    format: "OFFLINE",
    durationLabel: "4 oy",
    durationWeeks: 16,
    schedule: "Haftasiga 3 kun · 120 daqiqa",
    ageLabel: "16+",
    accent: "#E5560A",
    whoFor: ["Videografiyani kasb qilmoqchi boʻlganlar", "Mobilografiyadan keyingi bosqich", "Media studiyalarda ishlamoqchi boʻlganlar"],
    skills: ["Kamera va optika", "Yorugʻlik sxemalari", "Premiere Pro / DaVinci", "Color grading", "Ovoz", "Prodakshn jarayoni"],
    outcomes: ["Reklama rolik ishlab chiqarish", "Media studiyada videograf sifatida ishlash", "Portfolio: 3+ tugallangan ish"],
    curriculum: [
      { title: "Kamera", lessons: ["Ekspozitsiya", "Optika", "Harakat"] },
      { title: "Yorugʻlik va ovoz", lessons: ["Studiya yorugʻligi", "Tabiiy yorugʻlik", "Ovoz yozish"] },
      { title: "Montaj", lessons: ["Premiere Pro", "DaVinci Resolve", "Color grading"] },
      { title: "Prodakshn", lessons: ["Pre-production", "Sʼyomka kuni", "Post-production", "Diplom ishi"] },
    ],
    order: 6,
    status: "PUBLISHED",
  },
  {
    slug: "smm",
    title: "SMM",
    roleLabel: "SMM Manager",
    tagline: "Auditoriyani jamoaga aylantiring.",
    description:
      "Ijtimoiy tarmoqlarda brend yuritish: strategiya, kontent-reja, vizual, copywriting, tahlil va oʻsish. Real brendlar bilan amaliyot.",
    category: "marketing",
    level: "BEGINNER",
    format: "HYBRID",
    durationLabel: "3 oy",
    durationWeeks: 12,
    schedule: "Haftasiga 3 kun · 90 daqiqa",
    ageLabel: "16+",
    accent: "#FF6B1A",
    whoFor: ["Marketing sohasiga kirmoqchi boʻlganlar", "Oʻz biznesini oʻzi yuritmoqchi boʻlgan tadbirkorlar", "Freelance SMM boʻlmoqchi boʻlganlar"],
    skills: ["SMM strategiya", "Kontent-reja", "Copywriting", "Canva / Figma", "Instagram & Telegram", "Analitika"],
    outcomes: ["Brend uchun toʻliq SMM strategiya tuzish", "SMM menejer sifatida ishga kirish", "Oʻz mijozlaringizni topish"],
    curriculum: [
      { title: "Strategiya", lessons: ["Auditoriya tahlili", "Pozitsiyalash", "Kontent-reja"] },
      { title: "Kontent", lessons: ["Copywriting", "Vizual", "Reels va Stories"] },
      { title: "Oʻsish", lessons: ["Analitika", "Hamkorlik", "Real brend bilan amaliyot"] },
    ],
    order: 7,
    status: "PUBLISHED",
  },
  {
    slug: "target",
    title: "Target",
    roleLabel: "Targetologist",
    tagline: "Har bir soʻm natija bersin.",
    description:
      "Instagram, Facebook va Telegram’da maqsadli reklama: auditoriya, kreativ, byudjet, test va optimizatsiya. Real byudjet bilan amaliy mashgʻulotlar.",
    category: "marketing",
    level: "BEGINNER",
    format: "HYBRID",
    durationLabel: "2 oy",
    durationWeeks: 8,
    schedule: "Haftasiga 3 kun · 90 daqiqa",
    ageLabel: "16+",
    accent: "#FF5C00",
    whoFor: ["Reklama orqali daromad qilmoqchi boʻlganlar", "SMM mutaxassislari", "Tadbirkorlar"],
    skills: ["Meta Ads Manager", "Auditoriya segmentatsiyasi", "Kreativ va matn", "A/B test", "Analitika", "Telegram Ads"],
    outcomes: ["Reklama kampaniyasini mustaqil yuritish", "Targetolog sifatida mijozlar bilan ishlash", "ROI hisoblash va optimizatsiya"],
    curriculum: [
      { title: "Asoslar", lessons: ["Reklama kabineti", "Auditoriya", "Byudjet"] },
      { title: "Kampaniya", lessons: ["Kreativ", "Test", "Optimizatsiya"] },
      { title: "Amaliyot", lessons: ["Real loyiha", "Hisobot", "Mijoz bilan ishlash"] },
    ],
    order: 8,
    status: "PUBLISHED",
  },
];
