import type { Prisma } from "@prisma/client";

export const services: Prisma.ServiceCreateInput[] = [
  {
    slug: "reels-production",
    title: "Reels Production",
    tagline: "Vertikal, tez, konversiyaga yoʻnaltirilgan.",
    description: "Instagram va TikTok uchun ssenariydan tortib montajgacha toʻliq Reels ishlab chiqarish. Trendlar, hook va brend ovozi — bir formatda.",
    attributes: ["Creative", "Fast", "Vertical", "Conversion"],
    deliverables: ["Ssenariy va hook", "Sʼyomka", "Montaj va subtitrlar", "Oyiga 8–16 ta Reels"],
    process: [
      { step: "01", title: "Brif", description: "Maqsad, auditoriya va brend ovozini aniqlaymiz." },
      { step: "02", title: "Ssenariy", description: "Hook, tuzilma va CTA bilan ssenariylar tayyorlaymiz." },
      { step: "03", title: "Sʼyomka", description: "Studiya yoki lokatsiyada professional sʼyomka." },
      { step: "04", title: "Montaj", description: "Dinamik montaj, subtitr, rang va ovoz." },
    ],
    featured: true,
    order: 0,
    status: "PUBLISHED",
  },
  {
    slug: "youtube-production",
    title: "YouTube Production",
    tagline: "Uzoq formatda — kuchli brend.",
    description: "YouTube kanal strategiyasi, kontent rejalashtirish, sʼyomka, montaj va SEO. Brendingiz uchun barqaror auditoriya.",
    attributes: ["Long-form", "Strategy", "Storytelling", "SEO"],
    deliverables: ["Kanal strategiyasi", "Ssenariy", "Sʼyomka va montaj", "Thumbnail va SEO"],
    process: [
      { step: "01", title: "Strategiya", description: "Kanal pozitsiyasi va kontent ustunlari." },
      { step: "02", title: "Ishlab chiqarish", description: "Ssenariy, sʼyomka, montaj." },
      { step: "03", title: "Nashr", description: "Thumbnail, sarlavha, SEO va tahlil." },
    ],
    featured: true,
    order: 1,
    status: "PUBLISHED",
  },
  {
    slug: "smm",
    title: "SMM",
    tagline: "Ijtimoiy tarmoqlarda jonli brend.",
    description: "Strategiya, kontent-reja, vizual va matnlar, community management va oylik tahlil — brendingiz ijtimoiy tarmoqlarda tizimli yuritiladi.",
    attributes: ["Strategy", "Content", "Community", "Analytics"],
    deliverables: ["Oylik kontent-reja", "Postlar va Stories dizayni", "Copywriting", "Oylik hisobot"],
    order: 2,
    status: "PUBLISHED",
  },
  {
    slug: "target",
    title: "Target",
    tagline: "Toʻgʻri odamga, toʻgʻri vaqtda.",
    description: "Meta va Telegram’da maqsadli reklama kampaniyalari: auditoriya, kreativ, test va optimizatsiya. Byudjet natijaga ishlaydi.",
    attributes: ["Performance", "Data", "Testing", "ROI"],
    deliverables: ["Auditoriya tahlili", "Kreativlar", "Kampaniya boshqaruvi", "Haftalik hisobot"],
    order: 3,
    status: "PUBLISHED",
  },
  {
    slug: "permission-marketing",
    title: "Permission Marketing",
    tagline: "Ruxsat bilan — ishonch bilan.",
    description: "Telegram kanallar, email va chatbotlar orqali auditoriya bilan uzoq muddatli aloqa tizimi. Har bir xabar — qiymat.",
    attributes: ["Retention", "Automation", "Trust", "CRM"],
    deliverables: ["Kanal strategiyasi", "Avtomatlashtirilgan zanjirlar", "Chatbot", "Segmentatsiya"],
    order: 4,
    status: "PUBLISHED",
  },
  {
    slug: "video-production",
    title: "Video Production",
    tagline: "Kinematografik sifat.",
    description: "Reklama roliklari, imidj videolar, tadbirlar va mahsulot videolari — gʻoyadan yakuniy renderigacha professional prodakshn.",
    attributes: ["Cinematic", "Full-cycle", "Brand", "Quality"],
    deliverables: ["Gʻoya va ssenariy", "Pre-production", "Sʼyomka", "Post-production"],
    featured: true,
    order: 5,
    status: "PUBLISHED",
  },
  {
    slug: "content-creation",
    title: "Content Creation",
    tagline: "Kontent — brendning ovozi.",
    description: "Foto, video, matn va dizayn — brendingiz uchun barcha platformalarga mos kontent paketlari.",
    attributes: ["Multi-format", "Consistent", "Visual", "Voice"],
    deliverables: ["Foto sessiya", "Video kontent", "Matnlar", "Dizayn shablonlari"],
    order: 6,
    status: "PUBLISHED",
  },
  {
    slug: "personal-branding",
    title: "Personal Branding",
    tagline: "Siz — brendsiz.",
    description: "Tadbirkorlar va mutaxassislar uchun shaxsiy brend strategiyasi, vizual identifikatsiya va kontent tizimi.",
    attributes: ["Positioning", "Identity", "Authority", "Story"],
    deliverables: ["Pozitsiyalash", "Vizual uslub", "Kontent strategiya", "Media yuritish"],
    order: 7,
    status: "PUBLISHED",
  },
  {
    slug: "creative-ads",
    title: "Creative Ads",
    tagline: "Eʼtibor tortadigan reklama.",
    description: "Reklama uchun kreativ konsepsiyalar, statik va video kreativlar — sotuvga ishlaydigan gʻoyalar.",
    attributes: ["Idea", "Scroll-stopping", "Testing", "Performance"],
    deliverables: ["Kreativ konsepsiya", "Statik kreativlar", "Video kreativlar", "A/B variantlar"],
    order: 8,
    status: "PUBLISHED",
  },
  {
    slug: "instagram-management",
    title: "Instagram Management",
    tagline: "Instagram — toʻliq bizning zimmamizda.",
    description: "Profil dizaynidan tortib kunlik kontent, Stories, Reels va auditoriya bilan muloqotgacha — Instagram akkauntingizni toʻliq yuritamiz.",
    attributes: ["Full-service", "Daily", "Growth", "Engagement"],
    deliverables: ["Profil dizayni", "Kunlik Stories", "Postlar va Reels", "Community management"],
    order: 9,
    status: "PUBLISHED",
  },
];
